---
- name: Create AWS VPC
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: MyVPC
        cidr_block: 10.0.0.0/16
        region: us-east-1
        tags:
          Name: MyVPC
      register: vpc

    - name: Create Subnet 1
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.0.0.0/24
        map_public: yes
        resource_tags:
          Name: Subnet1-us-east-1a  # Include availability zone in the name
      register: subnet1

    - name: Create Subnet 2
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.0.1.0/24
        map_public: yes
        resource_tags:
          Name: Subnet2-us-east-1b  # Include availability zone in the name
      register: subnet2

    # The rest of your playbook...
